name: Verify Pull Request Labels

on:
  pull_request:
    types: [ready_for_review, review_requested, labeled, unlabeled]

jobs:
  verify_pr_labels:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install github actions dependencies
        uses: bahmutov/npm-install@v1.6.2

      - name: Verify Pull Request Labels
        uses: ./
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  git_log:
    name: Test git log
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Add PR base ref
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}

      - name: Git log
        run: |
          echo "git log"
          git log

          echo "git log revision"
          git log refs/remotes/origin/${{ github.base_ref }}..+refs/heads/${{ github.head_ref }} \
            --pretty=format:'%ae'

